/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;



import datastructures.linkedlist.LinkedList;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class LinkedListTest {

    @Test
    public void testInstantiateAnEmptyLinkedList() {
        LinkedList<Integer> linkedList = new LinkedList<>();
        assertTrue(linkedList.isEmpty());
    }

    @Test
    public void testInsertIntoTheLinkedList() {
        LinkedList<String> linkedList = new LinkedList<>();
        linkedList.insert("samara");
        linkedList.insert("sami");
        linkedList.insert("mohamad");
        assertFalse(linkedList.isEmpty());
    }

    @Test
    public void testTheHeadPropertyWillProperlyPointToTheFirstNodeInTheLinkedList() {
        LinkedList<Integer> linkedList = new LinkedList<>();
        linkedList.insert(2);
        linkedList.insert(1);
        linkedList.insert(0);
        // "{0} -> {1} -> {2} -> NULL"
        assertEquals(0, linkedList.head.value);
    }

    @Test
    public void testInsertMultipleNodes() {
        LinkedList<String> linkedList = new LinkedList<>();
        linkedList.insert("samara");
        linkedList.insert("sami");
        linkedList.insert("mohamad");
        assertEquals("samara", linkedList.head.next.next.value);
    }

    @Test
    public void testFindingValueWithinTheLinkedListThatExists() {
        LinkedList<String> linkedList = new LinkedList<>();
        linkedList.insert("samara");
        linkedList.insert("sami");
        linkedList.insert("mohamad");
        assertTrue(linkedList.includes("mohamad"));
    }

    @Test
    public void testSearchingForValueInTheLinkedListThatDoesNotExist() {
        LinkedList<String> linkedList = new LinkedList<>();
        linkedList.insert("samara");
        linkedList.insert("sami");
        linkedList.insert("mohamad");
        assertFalse(linkedList.includes("newName"));
    }

    @Test
    public void testPrintCollectionOfAllTheValuesThatExistInTheLinkedList() {
        LinkedList<String> linkedList = new LinkedList<>();
        linkedList.insert("samara");
        linkedList.insert("sami");
        linkedList.insert("mohamad");
        String expected = "{mohamad} -> {sami} -> {samara} -> NULL";
        assertEquals(expected, linkedList.toString());
    }

    @Test
    public void testPrintEmptyLinkedList() {
        LinkedList<String> linkedList = new LinkedList<>();
        String expected = "The LinkedList is Empty";
        assertEquals(expected, linkedList.toString());
    }
}

