/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class Library {

    public static void main(String[] args) {


        BinarySearchTree bst = new BinarySearchTree();

        bst.add(5);
        bst.add(3);
        bst.add(7);
        bst.add(2);
        bst.add(4);

        System.out.println(bst.traverseInOrder(bst.root));
        System.out.println(bst.traversePreOrder(bst.root));
        System.out.println(bst.traversePostOrder(bst.root));

        System.out.println("Contains 4 : " + bst.contains(4));
        System.out.println("Contains 10 : " + bst.contains(10));
    }

}
